name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 11

      - name: Checkstyle
        run: ./gradlew checkstyleMain

      - name: SpotBugs
        run: ./gradlew spotBugsMain spotBugsTest

      - name: Spotbugs report
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
            path: 'build/reports/spotbugs/main.xml'
        if: ${{ always() }}

      - name:  Checkstyle report
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'build/reports/checkstyle/main.xml'
        if: ${{ always() }}

  test:
    name: Build Plugin
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 11

      - name: Build the plugin
        run: ./gradlew buildPlugin

      - name: Run tests
        run: ./gradlew test

      - name: Publish code coverage report
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/reports/jacoco/test/jacocoTestReport.xml

  release:
    name: GitHub Release
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

      - name: Publish Release to GitHub
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
