name: Publish Plugin
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Jetbrains repostiory
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 11

      - name: Build Release binary
        run:  |
          echo ${GITHUB_REF##*v} > version.txt
          ./gradlew buildPlugin

      - name: Publish Plugin to Jetbrains Plugin Repository
        run: ./gradlew publishPlugin --stacktrace
        env:
          INTELIJ_PUBLISH_TOKEN: ${{ secrets.INTELIJ_PUBLISH_TOKEN }}
